### ISSUE TITLE
Roadmap public release

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-middle-layer#121]
- [x] having two vm for impresso
- [x] having two instance of IML running
- [x] named entities dummy data is there already in mysql!
- [x] image similarity
- [x] image upload
- [x] topic similarity at article level (top 3 better than threshold) - to be fixed, see issue #124 
- [x] fix CSV export and add mentions
- [x] add named entities in CSV export, if any
- [x] solr : fuzzy search, near function (see @e-maud comment)
- [x] word embedding collection in solr (similarity vector) integrate impresso embeddings

next

on hold:
- [ ] OCR quality assestment
- [ ] text reuse similarity

**Comment by e-maud** [comment]
Update SOLR:

**proximity search (near)**: OK sur prod 
`content_txt_fr:"déclaration femme"~2` 
`content_txt_fr:"déclaration femme"~3`

**fuzzy search**: OK sur prod
`content_txt_fr:paris~` : 1,476,353 hits
`content_txt_fr:paris` : 1,454,987 hits

Update word embeddings for query suggestions:
Technical test done with solr dense scorer plugin; next step: integrate impresso embeddings

**Comment by danieleguido** [comment]
thanks @e-maud
